name: Reusable workflow

on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '14' # should be 20 in link
      - name: Install dependencies 
        run: npm ci # npm install --no-audit --no-fund --no-optional
        shell: bash
      - name: Build
        run: npm run build
        shell: bash 
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
