name: "Deployment Pipeline"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - "opened"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Install depencies 
        run: npm install
      - name: Lint
        run: npm run eslint
