name: Tests

on:
  pull_request:
    types: [ opened, synchronize, edited ]
  push:
    branches: [preview, master] # TODO: Remove master

env:
  IS_NOT_WIP: |
    (
      'edited' != github.event.pull_request.action
      && !startsWith(github.event.pull_request.title, 'WIP')
    )
    || (
      'edited' == github.event.pull_request.action
      && startsWith(github.event.pull_request.changes.title.from, 'WIP')
      && !startsWith(github.event.pull_request.title, 'WIP')
    )

jobs:
  lint:
    if: ${{ env.IS_NOT_WIP }}
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14' # should be 20 in link
      - name: Install dependencies 
        run: npm ci # npm install --no-audit --no-fund --no-optional
      - name: Lint
        continue-on-error: true
        run: npm run eslint

  build:
    if: ${{ env.IS_NOT_WIP }}
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14' # should be 20 in link
      - name: Install dependencies 
        run: npm ci # npm install --no-audit --no-fund --no-optional
      - name: Build
        run: npm run build

  test:
    if: ${{ env.IS_NOT_WIP }}
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14' # should be 20 in link
      - name: Install dependencies 
        run: npm ci # npm install --no-audit --no-fund --no-optional
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
  
  debug:
    name: debug
    runs-on: ubuntu-20.04
    steps:
      - name: echo event
        run: |
          echo ${{github}}
          echo ${{github.event_name == 'push'}}
      - name: echo IS_NOT_WIP
        run: |
          echo ${{env.IS_NOT_WIP}}