name: Tests

on:
  pull_request:
    types: [ opened, synchronize, edited ]
  push:
    branches: [preview, master] # TODO: Remove master

env:
  IS_NOT_WIP: 

jobs:

  check-wip:
    if: |
      ${{ !((
        'edited' != github.event.pull_request.action
        && !startswith(github.event.pull_request.title, 'wip')
      )
      || (
        'edited' == github.event.pull_request.action
        && startswith(github.event.pull_request.changes.title.from, 'wip')
        && !startswith(github.event.pull_request.title, 'wip')
      )) }}
    runs-on: ubuntu-20.04
    steps:
      - run: exit 1

  lint:
    needs: [check-wip]
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14' # should be 20 in link
      - name: Install dependencies 
        run: npm ci # npm install --no-audit --no-fund --no-optional
      - name: Lint
        continue-on-error: true
        run: npm run eslint

  build:
    needs: [check-wip]
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14' # should be 20 in link
      - name: Install dependencies 
        run: npm ci # npm install --no-audit --no-fund --no-optional
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test:
    needs: [lint, build]
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14' # should be 20 in link
      - name: Install dependencies 
        run: npm ci # npm install --no-audit --no-fund --no-optional
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Test
        run: npm test
    
  deploy:
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - run: echo "not an actual deploy"