name: Tests

on:
  pull_request:
    types: [ opened, synchronize, edited ]
  push:
    branches: [preview, master] # TODO: Remove master

jobs:
  test:
    name: Test
    if: |
      (
        'edited' != github.event.pull_request.action
        && !startsWith(github.event.pull_request.title, 'WIP')
      )
      || (
        'edited' == github.event.pull_request.action
        && startsWith(github.event.pull_request.changes.title.from, 'WIP')
        && !startsWith(github.event.pull_request.title, 'WIP')
      )
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14' # should be 20 in link
      - name: Install dependencies 
        run: npm ci # npm install --no-audit --no-fund --no-optional
      - name: Lint
        continue-on-error: true
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: test
        run: npm test
      - name: echo event
        run: |
          echo ${{github.event_name}}
          echo ${{github.event_name == 'push'}}